### ISSUE TITLE
fdroid integration

### ISSUE THREAD

**Issue by vanous** [walley/guidepost#2]
Ahoy @walley , long time no speak :)

Can we get Guidepost into [f-droid](https://f-droid.org/en/)? i have never done that, but it should not be so difficult. I can try to help.

Does it make sense or is Fody the new way to do guide post pictures?

cheers
P.

**Comment by walley** [comment]
f-droid should be possible. App now uses latest Android studio, so they/fdroid should be able to build it without problems.

Support for fody api should also be possible, if anybody wants it.

**Comment by walley** [comment]
https://f-droid.org/docs/FAQ_-_App_Developers/?title=FAQ_-_App_Developers

**Comment by vanous** [comment]
Asi budeme muset projít celým tím vagrant builderem. Zatím jsem do toho nešel...

**Comment by walley** [comment]
problem budou knihovny co pouzivam, asi se to bude muset nejak zautomatizovat
apache:
commons-io-2.4.jar
httpclient-4.3.6.jar
httpcore-4.3.3.jar
httpmime-4.3.6.jar
koush:
koush/UrlImageViewHelper : urlimageviewhelper-1.0.4.jar

**Comment by vanous** [comment]
já jsem to tady pustil, stáhlo si to půlku internetu, ale nerozběhám vagrant, protože nebeží Virtualbox, protože pro 5.0.0 nemá debian kernel headers... (kbuild) a kvůli chybě v integraci iwlwifi v 5.2.0 nemám s 5.2.0 síť... možná to zkusím pustit po ethernetu... snad se podaří.

**Comment by vanous** [comment]
ahoj, mám kernel 5.3 + headers a wifina jede, takže budu pokračovat...

mmch, dotaz :) jak často se přegenerovávají data na osm.cz ? když doplnim area oblasti, je to tam téměř hned, ale points vypadá, že trvají přes noc?
díky

**Comment by vanous** [comment]
Pomalý, ale postup. Zkouším to nejprve u sebe. Zdá se, že ten 18GB vagrant není až tak potřeba a stačí kompilovat pouze pomocí fdroidu. Poslal jsem jim jednu svoji appku, tak uvidím jaký bude proces. Nemám u ní žádné žádné závislosti, tak by to mělo být pretty straightforward. https://gitlab.com/fdroid/fdroiddata/merge_requests/5348

**Comment by vanous** [comment]
Zatím jsem to dále nestudoval, ale toto mi teď prošlo:

fdroid import --url https://github.com/walley/guidepost.git
ANDROID_HOME=/home/vanous/android_sdk/ fdroid build -v -l org.walley.guidepost

s tímto meta yaml:
```
License: Unknown
SourceCode: https://github.com/walley/guidepost.git
IssueTracker: https://github.com/walley/guidepost.git/issues

RepoType: git
Repo: https://github.com/walley/guidepost.git

Builds:
  - versionName: '1.20'
    versionCode: 23
    commit: 556f94a815879a971aefbad0f50abef2caa96059
    subdir: guidepost
    gradle:
      - yes
    srclibs:
      - CommonsIO@2.4
      - ApacheHttpClient@4.3.6
      - ApacheHttpCore@4.3.3
      - OSMBonusPack@v5.3

AutoUpdateMode: None
UpdateCheckMode: Tags
```

možná je to proto, že některé knihovny jsou pořád v libs, nepoužil jsem svůj fork a nesmazal je, zkusím pak...

**Comment by walley** [comment]
jak casto pregenerovavaji cokoliv na osm.cz netusim:(

**Comment by vanous** [comment]
CommonsIO a OSMBonusPack už mi jdou, ale pro to Apache potřebuji asi dowgradovat javu...

[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
```
Builds:
  - versionName: 1.20
    versionCode: 23
    commit: 89478dfde86a1e433b0b0f0f2f34032bd8d30331
    subdir: guidepost
    gradle:
      - yes
    srclibs:
      - CommonsIO@2.4
      - OSMBonusPack@v5.3
      - ApacheHttpCore@4.3.3
      - ApacheHttpClient@4.3.3
    prebuild:
      - mkdir libs
      - pushd $$CommonsIO$$
      - $$MVN3$$ package
      - popd
      - cp $$CommonsIO$$/target/commons-io-2.4.jar libs/
      - pushd $$ApacheHttpClient$$/httpclient/
      - $$MVN3$$ package
      - popd
      - cp $$ApacheHttpClient$$/httpclient/target/httpclient-4.3.3.jar libs/
      - pushd $$ApacheHttpCore$$/httpcore
      - $$MVN3$$ package
      - popd
      - cp $$ApacheHttpCore$$/httpcore/target/httpcore-4.3.3.jar libs/
      - sed -i -e '/slf4j-android/d' $$OSMBonusPack$$/build.gradle
      - cp -r $$OSMBonusPack$$ ../
```

**Comment by walley** [comment]
no ja mam v projektu nastavenou javu 1.7

**Comment by vanous** [comment]
ok, už builduju fdroidem vše kromě urlimageviewhelper-1.0.4.jar , odkud se to bere? koush tam má pouze 1.0.1? díky

**Comment by vanous** [comment]
ok, mám to
```
INFO: success: org.walley.guidepost
INFO: Finished
INFO: 1 build succeeded
```

```
License: Unknown
SourceCode: https://github.com/walley/guidepost.git
IssueTracker: https://github.com/walley/guidepost.git/issues

RepoType: git
Repo: https://github.com/walley/guidepost.git

Builds:
  - versionName: '1.20'
    versionCode: 23
    commit: '1.20'
    subdir: guidepost
    gradle:
      - yes
    srclibs:
      - CommonsIO@2.4
      - ApacheHttpCore@4.3.3
      - ApacheHttpClient@4.3.6
    prebuild:
      - rm libs/*
        #- mkdir libs
      - pwd
      - cp ../../build.gradle ./
      - cp ../../build.gradle.project ../build.gradle
        #- sed -i -e '/slf4j-android/d' $$OSMBonusPack$$/build.gradle
        #- cp -r $$OSMBonusPack$$ ../
        #- gradle build
      - pushd $$CommonsIO$$
      - $$MVN3$$ package -Dmaven.test.skip=true
      - popd
      - cp $$CommonsIO$$/target/commons-io-2.4.jar libs/
      - pushd $$ApacheHttpClient$$/httpclient/
      - sed -i -e 's/<packaging>jar<\/packaging>/<packaging>jar<\/packaging><properties> <maven.compiler.source>1.6<\/maven.compiler.source> <maven.compiler.target>1.6<\/maven.compiler.target> <\/properties>/g' pom.xml
      - $$MVN3$$ package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
        #- $$MVN3$$ package
      - popd
      - cp $$ApacheHttpClient$$/httpclient/target/httpclient-4.3.6.jar libs/
      - pushd $$ApacheHttpCore$$/httpcore
      - sed -i -e 's/<packaging>jar<\/packaging>/<packaging>jar<\/packaging><properties> <maven.compiler.source>1.6<\/maven.compiler.source> <maven.compiler.target>1.6<\/maven.compiler.target> <\/properties>/g' pom.xml
      - $$MVN3$$ package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
      - popd
      - cp $$ApacheHttpCore$$/httpcore/target/httpcore-4.3.3.jar libs/
      - pushd $$ApacheHttpClient$$/httpmime/
      - sed -i -e 's/<packaging>jar<\/packaging>/<packaging>jar<\/packaging><properties> <maven.compiler.source>1.6<\/maven.compiler.source> <maven.compiler.target>1.6<\/maven.compiler.target> <\/properties>/g' pom.xml
      - $$MVN3$$ package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
        #- $$MVN3$$ package
      - popd
      - cp $$ApacheHttpClient$$/httpmime/target/httpmime-4.3.6.jar libs/


AutoUpdateMode: None
UpdateCheckMode: Tags
```

top level build.gradle:

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
    }
}

allprojects {
    repositories {
        maven { url "https://jitpack.io" }
        jcenter()
        google()
        mavenCentral()
    }
}

```


lokalní build.gradle dependencies:
```
dependencies {
//    implementation files('libs/commons-io-2.4.jar')
    implementation files('libs/httpclient-4.3.6.jar')
    implementation files('libs/httpcore-4.3.3.jar')
    implementation files('libs/httpmime-4.3.6.jar')
    //implementation files('libs/urlimageviewhelper-1.0.4.jar')
    //implementation files('libs/osmbonuspack_6.6.0.aar')
    implementation 'com.koushikdutta.urlimageviewhelper:urlimageviewhelper:1.0.4'
    implementation 'com.github.MKergall:osmbonuspack:6.6.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.koushikdutta.ion:ion:2.+'
    implementation 'org.osmdroid:osmdroid-android:6.1.0'
    implementation 'commons-io:commons-io:2.4'
}
```
